app:
    resource: "@AppBundle/Controller/"
    type:     annotation

cinemas:
    type:      rest
    resource:  AppBundle\Controller\CinemaController

films:
    type:      rest
    resource:  AppBundle\Controller\FilmController

salles:
    type:      rest
    resource:  AppBundle\Controller\Cinema\SalleController

# app/config/routing.yml
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }