AppBundle\Entity\Cinema:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [nom]
    properties:
        nom:
            - NotBlank: ~
            - Type: string
        adresse:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\Salle:
    properties:
        nom:
            - NotBlank: ~
            - Type: string
        capacite:
            - NotBlank: ~
            - Type: numeric
            - GreaterThan:
                value: 0

