<?php

namespace AdminBundle\Repository;

/**
 * CinemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinemaRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {
        //création du queryBuilder paramétré avec l'alias de l'entité cinéma
        $queryBuilder = $this->createQueryBuilder('c');
        // récupération de la query à partir du queryBuilder
        $query = $queryBuilder->getQuery();
        //récupération du résultat à partir de la query
        $results = $query->getResult();
        // on returne les résultats
        return $results;
    }

    public function findAllBetween()
    {
        $queryBuilder = $this->createQueryBuilder('c');
        $query = $queryBuilder->where('c.dateouverture between :start and :end')
            ->setParameter('start', new \DateTime('2017-12-04 00:00:00'))
            ->setParameter('end', new \DateTime('2017-12-04 00:00:00'));
        return $query->getResult();
    }

    // DQL
    public function myFindAllDQL() {
        $query = $this->_em->createQuery('select c from AdminBundle:Cinema c');
        return $query->getResult();
    }

    public function myFindNomDQL() {
        $query = $this->_em->createQuery('select c from AdminBundle:Cinema c where c.nom like \'%CGR%\'');
        return $query->getResult();
    }
}
