<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCwxawt3\appDevProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCwxawt3/appDevProjectContainer.php') {
    touch(__DIR__.'/ContainerCwxawt3.legacy');

    return;
}

if (!\class_exists(appDevProjectContainer::class, false)) {
    \class_alias(\ContainerCwxawt3\appDevProjectContainer::class, appDevProjectContainer::class, false);
}

return new \ContainerCwxawt3\appDevProjectContainer(array(
    'container.build_hash' => 'Cwxawt3',
    'container.build_id' => 'c74286e0',
    'container.build_time' => 1519822910,
));
