<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4juove9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4juove9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4juove9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4juove9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4juove9\appDevDebugProjectContainer(array(
    'container.build_hash' => '4juove9',
    'container.build_id' => '555e4341',
    'container.build_time' => 1519825873,
));
